# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.19-s055_1 on Tue Dec 17 16:04:17 CET 2024

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design CiscV

create_clock -name "CLK" -period 100.0 -waveform {0.0 50.0} [get_ports clk]
set_load -pin_load -min 0.01 [get_ports {com_enable[0]}]
set_load -pin_load -max 0.1 [get_ports {com_enable[0]}]
set_load -pin_load -min 0.01 [get_ports {m_active[0]}]
set_load -pin_load -max 0.1 [get_ports {m_active[0]}]
set_load -pin_load -min 0.01 [get_ports {addr[1]}]
set_load -pin_load -max 0.1 [get_ports {addr[1]}]
set_load -pin_load -min 0.01 [get_ports {addr[0]}]
set_load -pin_load -max 0.1 [get_ports {addr[0]}]
set_load -pin_load -min 0.01 [get_ports {m_data[1]}]
set_load -pin_load -max 0.1 [get_ports {m_data[1]}]
set_load -pin_load -min 0.01 [get_ports {m_data[0]}]
set_load -pin_load -max 0.1 [get_ports {m_data[0]}]
set_load -pin_load -min 0.01 [get_ports {rd_data_out[4]}]
set_load -pin_load -max 0.1 [get_ports {rd_data_out[4]}]
set_load -pin_load -min 0.01 [get_ports {rd_data_out[3]}]
set_load -pin_load -max 0.1 [get_ports {rd_data_out[3]}]
set_load -pin_load -min 0.01 [get_ports {rd_data_out[2]}]
set_load -pin_load -max 0.1 [get_ports {rd_data_out[2]}]
set_load -pin_load -min 0.01 [get_ports {rd_data_out[1]}]
set_load -pin_load -max 0.1 [get_ports {rd_data_out[1]}]
set_load -pin_load -min 0.01 [get_ports {rd_data_out[0]}]
set_load -pin_load -max 0.1 [get_ports {rd_data_out[0]}]
set_load -pin_load -min 0.01 [get_ports {rs1_data_out[4]}]
set_load -pin_load -max 0.1 [get_ports {rs1_data_out[4]}]
set_load -pin_load -min 0.01 [get_ports {rs1_data_out[3]}]
set_load -pin_load -max 0.1 [get_ports {rs1_data_out[3]}]
set_load -pin_load -min 0.01 [get_ports {rs1_data_out[2]}]
set_load -pin_load -max 0.1 [get_ports {rs1_data_out[2]}]
set_load -pin_load -min 0.01 [get_ports {rs1_data_out[1]}]
set_load -pin_load -max 0.1 [get_ports {rs1_data_out[1]}]
set_load -pin_load -min 0.01 [get_ports {rs1_data_out[0]}]
set_load -pin_load -max 0.1 [get_ports {rs1_data_out[0]}]
set_load -pin_load -min 0.01 [get_ports {rs2_data_out[4]}]
set_load -pin_load -max 0.1 [get_ports {rs2_data_out[4]}]
set_load -pin_load -min 0.01 [get_ports {rs2_data_out[3]}]
set_load -pin_load -max 0.1 [get_ports {rs2_data_out[3]}]
set_load -pin_load -min 0.01 [get_ports {rs2_data_out[2]}]
set_load -pin_load -max 0.1 [get_ports {rs2_data_out[2]}]
set_load -pin_load -min 0.01 [get_ports {rs2_data_out[1]}]
set_load -pin_load -max 0.1 [get_ports {rs2_data_out[1]}]
set_load -pin_load -min 0.01 [get_ports {rs2_data_out[0]}]
set_load -pin_load -max 0.1 [get_ports {rs2_data_out[0]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[31]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[31]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[30]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[30]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[29]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[29]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[28]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[28]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[27]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[27]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[26]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[26]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[25]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[25]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[24]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[24]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[23]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[23]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[22]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[22]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[21]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[21]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[20]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[20]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[19]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[19]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[18]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[18]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[17]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[17]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[16]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[16]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[15]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[15]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[14]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[14]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[13]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[13]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[12]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[12]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[11]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[11]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[10]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[10]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[9]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[9]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[8]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[8]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[7]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[7]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[6]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[6]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[5]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[5]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[4]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[4]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[3]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[3]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[2]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[2]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[1]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[1]}]
set_load -pin_load -min 0.01 [get_ports {result_bus_out[0]}]
set_load -pin_load -max 0.1 [get_ports {result_bus_out[0]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[31]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[31]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[30]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[30]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[29]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[29]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[28]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[28]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[27]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[27]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[26]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[26]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[25]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[25]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[24]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[24]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[23]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[23]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[22]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[22]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[21]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[21]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[20]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[20]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[19]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[19]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[18]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[18]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[17]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[17]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[16]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[16]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[15]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[15]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[14]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[14]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[13]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[13]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[12]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[12]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[11]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[11]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[10]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[10]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[9]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[9]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[8]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[8]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[7]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[7]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[6]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[6]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[5]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[5]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[4]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[4]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[3]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[3]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[2]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[2]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[1]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[1]}]
set_load -pin_load -min 0.01 [get_ports {op1_bus_out[0]}]
set_load -pin_load -max 0.1 [get_ports {op1_bus_out[0]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[31]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[31]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[30]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[30]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[29]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[29]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[28]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[28]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[27]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[27]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[26]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[26]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[25]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[25]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[24]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[24]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[23]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[23]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[22]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[22]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[21]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[21]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[20]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[20]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[19]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[19]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[18]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[18]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[17]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[17]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[16]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[16]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[15]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[15]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[14]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[14]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[13]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[13]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[12]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[12]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[11]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[11]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[10]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[10]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[9]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[9]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[8]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[8]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[7]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[7]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[6]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[6]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[5]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[5]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[4]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[4]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[3]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[3]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[2]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[2]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[1]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[1]}]
set_load -pin_load -min 0.01 [get_ports {op2_bus_out[0]}]
set_load -pin_load -max 0.1 [get_ports {op2_bus_out[0]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[31]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[31]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[30]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[30]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[29]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[29]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[28]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[28]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[27]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[27]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[26]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[26]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[25]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[25]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[24]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[24]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[23]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[23]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[22]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[22]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[21]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[21]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[20]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[20]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[19]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[19]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[18]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[18]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[17]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[17]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[16]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[16]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[15]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[15]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[14]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[14]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[13]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[13]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[12]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[12]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[11]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[11]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[10]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[10]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[9]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[9]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[8]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[8]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[7]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[7]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[6]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[6]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[5]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[5]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[4]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[4]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[3]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[3]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[2]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[2]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[1]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[1]}]
set_load -pin_load -min 0.01 [get_ports {op1_alt_out[0]}]
set_load -pin_load -max 0.1 [get_ports {op1_alt_out[0]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[31]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[31]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[30]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[30]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[29]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[29]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[28]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[28]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[27]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[27]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[26]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[26]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[25]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[25]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[24]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[24]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[23]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[23]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[22]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[22]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[21]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[21]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[20]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[20]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[19]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[19]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[18]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[18]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[17]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[17]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[16]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[16]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[15]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[15]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[14]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[14]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[13]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[13]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[12]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[12]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[11]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[11]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[10]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[10]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[9]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[9]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[8]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[8]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[7]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[7]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[6]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[6]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[5]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[5]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[4]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[4]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[3]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[3]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[2]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[2]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[1]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[1]}]
set_load -pin_load -min 0.01 [get_ports {op2_alt_out[0]}]
set_load -pin_load -max 0.1 [get_ports {op2_alt_out[0]}]
set_load -pin_load -min 0.01 [get_ports {result_select_out[2]}]
set_load -pin_load -max 0.1 [get_ports {result_select_out[2]}]
set_load -pin_load -min 0.01 [get_ports {result_select_out[1]}]
set_load -pin_load -max 0.1 [get_ports {result_select_out[1]}]
set_load -pin_load -min 0.01 [get_ports {result_select_out[0]}]
set_load -pin_load -max 0.1 [get_ports {result_select_out[0]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[31]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[31]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[30]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[30]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[29]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[29]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[28]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[28]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[27]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[27]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[26]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[26]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[25]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[25]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[24]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[24]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[23]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[23]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[22]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[22]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[21]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[21]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[20]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[20]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[19]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[19]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[18]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[18]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[17]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[17]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[16]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[16]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[15]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[15]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[14]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[14]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[13]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[13]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[12]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[12]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[11]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[11]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[10]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[10]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[9]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[9]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[8]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[8]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[7]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[7]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[6]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[6]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[5]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[5]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[4]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[4]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[3]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[3]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[2]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[2]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[1]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[1]}]
set_load -pin_load -min 0.01 [get_ports {pc_out[0]}]
set_load -pin_load -max 0.1 [get_ports {pc_out[0]}]
set_false_path -from [get_ports {sreset[0]}]
set_clock_gating_check -setup 0.0 
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {com_enable[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {m_active[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {addr[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {addr[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {m_data[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {m_data[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rd_data_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rd_data_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rd_data_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rd_data_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rd_data_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rs1_data_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rs1_data_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rs1_data_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rs1_data_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rs1_data_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rs2_data_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rs2_data_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rs2_data_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rs2_data_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {rs2_data_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[31]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[30]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[29]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[28]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[27]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[26]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[25]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[24]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[23]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[22]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[21]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[20]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[19]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[18]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[17]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[16]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[15]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[14]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[13]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[12]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[11]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[10]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[9]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[8]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[7]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[6]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[5]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_bus_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[31]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[30]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[29]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[28]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[27]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[26]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[25]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[24]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[23]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[22]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[21]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[20]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[19]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[18]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[17]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[16]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[15]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[14]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[13]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[12]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[11]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[10]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[9]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[8]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[7]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[6]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[5]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_bus_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[31]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[30]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[29]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[28]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[27]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[26]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[25]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[24]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[23]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[22]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[21]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[20]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[19]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[18]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[17]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[16]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[15]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[14]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[13]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[12]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[11]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[10]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[9]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[8]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[7]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[6]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[5]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_bus_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[31]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[30]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[29]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[28]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[27]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[26]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[25]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[24]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[23]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[22]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[21]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[20]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[19]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[18]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[17]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[16]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[15]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[14]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[13]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[12]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[11]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[10]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[9]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[8]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[7]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[6]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[5]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op1_alt_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[31]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[30]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[29]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[28]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[27]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[26]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[25]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[24]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[23]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[22]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[21]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[20]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[19]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[18]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[17]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[16]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[15]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[14]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[13]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[12]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[11]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[10]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[9]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[8]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[7]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[6]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[5]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {op2_alt_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_select_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_select_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {result_select_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[31]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[30]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[29]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[28]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[27]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[26]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[25]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[24]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[23]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[22]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[21]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[20]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[19]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[18]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[17]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[16]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[15]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[14]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[13]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[12]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[11]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[10]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[9]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[8]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[7]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[6]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[5]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {pc_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {com_enable[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {m_active[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {addr[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {addr[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {m_data[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {m_data[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rd_data_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rd_data_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rd_data_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rd_data_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rd_data_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rs1_data_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rs1_data_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rs1_data_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rs1_data_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rs1_data_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rs2_data_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rs2_data_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rs2_data_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rs2_data_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {rs2_data_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[31]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[30]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[29]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[28]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[27]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[26]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[25]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[24]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[23]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[22]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[21]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[20]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[19]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[18]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[17]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[16]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[15]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[14]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[13]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[12]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[11]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[10]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[9]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[8]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[7]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[6]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[5]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_bus_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[31]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[30]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[29]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[28]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[27]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[26]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[25]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[24]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[23]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[22]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[21]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[20]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[19]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[18]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[17]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[16]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[15]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[14]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[13]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[12]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[11]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[10]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[9]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[8]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[7]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[6]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[5]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_bus_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[31]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[30]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[29]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[28]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[27]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[26]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[25]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[24]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[23]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[22]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[21]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[20]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[19]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[18]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[17]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[16]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[15]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[14]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[13]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[12]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[11]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[10]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[9]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[8]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[7]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[6]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[5]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_bus_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[31]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[30]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[29]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[28]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[27]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[26]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[25]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[24]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[23]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[22]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[21]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[20]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[19]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[18]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[17]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[16]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[15]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[14]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[13]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[12]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[11]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[10]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[9]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[8]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[7]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[6]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[5]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op1_alt_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[31]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[30]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[29]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[28]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[27]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[26]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[25]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[24]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[23]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[22]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[21]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[20]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[19]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[18]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[17]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[16]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[15]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[14]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[13]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[12]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[11]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[10]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[9]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[8]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[7]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[6]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[5]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {op2_alt_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_select_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_select_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {result_select_out[0]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[31]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[30]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[29]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[28]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[27]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[26]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[25]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[24]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[23]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[22]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[21]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[20]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[19]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[18]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[17]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[16]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[15]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[14]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[13]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[12]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[11]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[10]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[9]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[8]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[7]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[6]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[5]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[4]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[3]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[2]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[1]}]
set_output_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {pc_out[0]}]
set_input_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {s_active[0]}]
set_input_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {s_data[1]}]
set_input_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {s_data[0]}]
set_input_delay -clock [get_clocks CLK] -network_latency_included -add_delay -max 0.2 [get_ports {sreset[0]}]
set_input_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {s_active[0]}]
set_input_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {s_data[1]}]
set_input_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {s_data[0]}]
set_input_delay -clock [get_clocks CLK] -network_latency_included -add_delay -min 0.1 [get_ports {sreset[0]}]
set_operating_conditions PVT_1P8V_25C
set_driving_cell -lib_cell BUFX2 -library KISTA_SOI_STDLIB2_CCS_TT -pin "Y" [get_ports clk]
set_driving_cell -lib_cell BUFX2 -library KISTA_SOI_STDLIB2_CCS_TT -pin "Y" [get_ports {s_active[0]}]
set_driving_cell -lib_cell BUFX2 -library KISTA_SOI_STDLIB2_CCS_TT -pin "Y" [get_ports {s_data[1]}]
set_driving_cell -lib_cell BUFX2 -library KISTA_SOI_STDLIB2_CCS_TT -pin "Y" [get_ports {s_data[0]}]
set_driving_cell -lib_cell BUFX2 -library KISTA_SOI_STDLIB2_CCS_TT -pin "Y" [get_ports {sreset[0]}]
set_wire_load_mode "enclosed"
set_clock_latency  0.2 [get_clocks CLK]
set_clock_uncertainty -setup 0.3 [get_clocks CLK]
set_clock_uncertainty -hold 0.2 [get_clocks CLK]
